name: todo_getx
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  audio_waveforms: ^1.0.4
  audioplayers: ^5.2.1
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  record: ^5.0.4
  step_progress_indicator: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
